### ISSUE TITLE
Feature Request: Enhanced descriptions for purchased items

### ISSUE THREAD

**Issue by WilliamRoyNelson** [spencers145/SharkGame#10]
When descriptions are enabled, purchasable items should show a preview of what the purchase will do.

Example:

```
Catch Fish
Use your natural shark prowess to find and catch a fish.
fish +1
```

```
Recruit shark
Cost: 125 fish
Recruit a shark to help catch more fish.
fish +1.5/s
```

**Comment by spencers145** [comment]
This is something I am actively considering, and the current idea is that when mousing over purchasable items, a small box appears which very succinctly shows which resources it produces and consumes.

However, I lack the understanding of CSS and HTML to do this. I could find another workaround in the meantime; another way to display that information in a simple manner. I would need to experiment with descriptions and perhaps with additional forms of UI which are more within my reach.

**Comment by spencers145** [comment]
Implemented this feature.
