### ISSUE TITLE
Typo: EFFICIENY -> EFFICIENCY

### ISSUE THREAD

**Issue by WilliamRoyNelson** [spencers145/SharkGame#9]
### https://github.com/spencers145/SharkGame/blob/6640e994076b5f2a507ef2f4e552f59be37e782b/js/tabs/recycler.js#L350

Should be
`"<b>%<br/>EFFICIENCY</b><br/><br/>EQUIVALENT TO:<br/>" +`

**Comment by spencers145** [comment]
Ah, good catch. The change will take effect next commit.
